
- name: install docker and kubectl
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - docker_install
    - k8s_install

- name: create cluster
  hosts: kube_control_plane
  become: yes
  remote_user: ubuntu
  roles:
    - k8s_create_cluster

- name: node invite
  hosts: kube_node
  become: yes
  remote_user: ubuntu
  roles:
    - node_invite


