
all:
    hosts: 
        master-0:
            ansible_host: 89.169.139.171
            ip: 10.10.1.21
            access_ip: 89.169.139.171
            ansible_user: ubuntu
        worker-0:
            ansible_host: 130.193.49.85
            ip: 10.10.1.19
            access_ip: 130.193.49.85
            ansible_user: ubuntu
        worker-1:
            ansible_host: 158.160.9.115
            ip: 10.10.2.27
            access_ip: 158.160.9.115
            ansible_user: ubuntu
