all:
    hosts:
        k8s-master:
            ansible_host:
            ip: 10.10.1.24
            ansible_user: ubuntu
            ansible_ssh_common_args: -J ubuntu@89.169.139.110

        k8s-worker-1:
            ansible_host:
            ip: 10.10.1.15
            ansible_user: ubuntu
            ansible_ssh_common_args: -J ubuntu@89.169.139.110
        
        k8s-worker-2:
            ansible_host:
            ip: 10.10.2.31
            ansible_user: ubuntu
            ansible_ssh_common_args: -J ubuntu@89.169.139.110
         
        
        
kube_control_plane:
    hosts: 
        k8s-master:
kube_node:
    hosts:
        k8s-worker-1:
        k8s-worker-2:
etcd:
    hosts: 
        k8s-master:

