---
  - name: Configuration Kubernetes nodes
    hosts: all
    become: true
    vars:
      sysctl_param:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables
      packages:
        - kubelet
        - kubeadm
        - kubectl
  
    tasks:
    # Отключаем файл подкачки
      - name: Turn off swap
        ansible.builtin.command: swapoff -a
  
      - name: Load modules
        ansible.builtin.shell: |
          modprobe overlay
          modprobe br_netfilter
  
      - name: Add configuration for automatically modules loaded
        ansible.builtin.blockinfile:
          path: /etc/modules-load.d/containerd.conf
          create: true
          block: |
            overlay
            br_netfilter
  
      - name: Setup sysctl params
        ansible.posix.sysctl:
          name: "{{ item }}"
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes
          sysctl_file: /etc/sysctl.d/k8s.conf
        loop:
          "{{ sysctl_param }}"
  
      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
  
      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present
  
      - name: Install the containerd package
        ansible.builtin.apt:
          name: containerd
          state: present
  
      - name: Create a configuration file for containerd and set it to default
        ansible.builtin.shell: |
          mkdir -p /etc/containerd
          containerd config default | sudo tee /etc/containerd/config.toml
  
      - name: Set cgroupdriver to systemd
        ansible.builtin.lineinfile:
          path: /etc/containerd/config.toml
          regexp: 'SystemdCgroup = false'
          line: SystemdCgroup = true
  
      - name: Restart containerd package
        ansible.builtin.systemd:
          name: containerd
          state: restarted
          enabled: true
  
      - name: mkdir keyrings
        become: true
        ansible.builtin.shell: mkdir /etc/apt/keyrings | sudo chmod 777 /etc/apt/keyrings 
  
      - name: Add gpg key k8s
        become: true
        apt_key:
          url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
          state: present
          keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  
      - name: Add the Kubernetes repository
        become: true
        apt_repository:
          repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
          state: present
  
      - name: Update Repository cache
        become: true
        ansible.builtin.apt:
          update_cache: true
  
      - name: Install all Kubernetes modules (kubelet, kubeadm, kubectl)
        become: true
        ansible.builtin.apt:
          name: "{{ packages }}"
          state: present
  
      - name: Enable kubelet
        become: true
        ansible.builtin.systemd:
          name: kubelet
          state: started
          enabled: true